spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/encasa
    username: encasa_user
    password: encasa_pass
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          timezone: UTC
  

server:
  port: 8080

jwt:
  secret: encasa-super-secret-key-que-luego-va-a-env
  expiration: 86400000
